# Generated by Django 5.0.6 on 2026-06-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.PositiveIntegerField(help_text="FCFA")),
                ("currency", models.CharField(default="XOF", max_length=5)),
                (
                    "operator",
                    models.CharField(
                        choices=[("orange", "Orange Money CI"), ("wave", "Wave"), ("mtn", "MTN MoMo")], max_length=10
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("tx_ref", models.CharField(max_length=100, unique=True)),
                ("operator_tx_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("escrow", "Séquestré"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("training", "Formation"),
                            ("tutoring", "Cours particulier"),
                            ("subscription", "Abonnement directeur"),
                            ("commission", "Commission recrutement"),
                            ("retake_fee", "Frais de rattrapage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_data", models.JSONField(default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("reviewed", "En révision"),
                            ("resolved", "Résolu"),
                            ("closed", "Clôturé"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="disputes", to="payments.payment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Litige",
                "verbose_name_plural": "Litiges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reversal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.PositiveIntegerField()),
                (
                    "operator",
                    models.CharField(
                        choices=[("orange", "Orange Money CI"), ("wave", "Wave"), ("mtn", "MTN MoMo")], max_length=10
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("sent", "Envoyé"), ("failed", "Échoué")],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reversals", to="payments.payment"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reversals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reversement",
                "verbose_name_plural": "Reversements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "status"], name="payments_pa_user_id_01767a_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tx_ref"], name="payments_pa_tx_ref_c37bc1_idx"),
        ),
    ]
