# Generated by Django 5.0.6 on 2026-08-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_card', 'Carte bancaire')], default='mobile_money', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operator',
            field=models.CharField(blank=True, choices=[('orange', 'Orange Money CI'), ('wave', 'Wave'), ('mtn', 'MTN MoMo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('training', 'Formation'), ('tutoring', 'Cours particulier'), ('subscription', 'Abonnement directeur'), ('commission', 'Commission recrutement'), ('retake_fee', 'Frais de rattrapage'), ('payroll_invoice', 'Facture paie enseignants')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
