# Generated by Django 5.0.6 on 2026-09-06 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0013_schoolgroup_directorprofile_school_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeInstallment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField(help_text="FCFA")),
                ("due_date", models.DateField()),
            ],
            options={
                "verbose_name": "Tranche de frais de scolarité",
                "verbose_name_plural": "Tranches de frais de scolarité",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="FeePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_paid", models.PositiveIntegerField(help_text="FCFA")),
                (
                    "payment_channel",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Virement"),
                            ("other", "Autre"),
                        ],
                        default="cash",
                        max_length=15,
                    ),
                ),
                ("paid_at", models.DateTimeField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fee_payments", to="users.child"
                    ),
                ),
                (
                    "fee_installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tuition.feeinstallment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement de frais de scolarité",
                "verbose_name_plural": "Paiements de frais de scolarité",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "school_year",
                    models.CharField(help_text="Ex. 2025-2026", max_length=9, verbose_name="Année scolaire"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_schedules",
                        to="users.directorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Échéancier de frais de scolarité",
                "verbose_name_plural": "Échéanciers de frais de scolarité",
                "unique_together": {("establishment", "school_year")},
            },
        ),
        migrations.AddField(
            model_name="feeinstallment",
            name="fee_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="installments", to="tuition.feeschedule"
            ),
        ),
    ]
