# Generated by Django 5.0.6 on 2026-06-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("new_job_offer", "Nouvelle offre d'emploi"),
                            ("application_viewed", "Candidature consultée"),
                            ("exam_available", "Examen disponible"),
                            ("exam_result", "Résultat d'examen"),
                            ("session_confirmed", "Séance confirmée"),
                            ("session_cancelled", "Séance annulée"),
                            ("payment_received", "Paiement reçu"),
                            ("cert_expiry", "Alerte expiration certification"),
                            ("new_message", "Nouveau message"),
                            ("exercise_submitted", "Copie soumise"),
                            ("correction_ready", "Correction disponible"),
                            ("recruitment", "Recrutement confirmé"),
                            ("stage_update", "Mise à jour stage"),
                            ("system", "Système"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("push", "Push mobile"), ("sms", "SMS"), ("email", "Email"), ("inapp", "In-app")],
                        default="inapp",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Payload extra — ex: {url, object_id, object_type}"),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"),
                    models.Index(fields=["user", "notif_type"], name="notificatio_user_id_3ffb31_idx"),
                ],
            },
        ),
    ]
