# Generated by Django 5.0.6 on 2026-07-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notif_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("new_job_offer", "Nouvelle offre d'emploi"),
                    ("application_viewed", "Candidature consultée"),
                    ("exam_available", "Examen disponible"),
                    ("exam_result", "Résultat d'examen"),
                    ("session_confirmed", "Séance confirmée"),
                    ("session_cancelled", "Séance annulée"),
                    ("payment_received", "Paiement reçu"),
                    ("cert_expiry", "Alerte expiration certification"),
                    ("new_message", "Nouveau message"),
                    ("exercise_submitted", "Copie soumise"),
                    ("correction_ready", "Correction disponible"),
                    ("recruitment", "Recrutement confirmé"),
                    ("stage_update", "Mise à jour stage"),
                    ("class_assignment", "Affectation à une matière"),
                    ("enrollment_update", "Mise à jour de scolarité"),
                    ("system", "Système"),
                ],
                max_length=30,
            ),
        ),
    ]
