# Generated by Django 5.0.6 on 2026-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_alter_notification_notif_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("new_job_offer", "Nouvelle offre d'emploi"),
                    ("application_viewed", "Candidature consultée"),
                    ("exam_available", "Examen disponible"),
                    ("exam_result", "Résultat d'examen"),
                    ("session_confirmed", "Séance confirmée"),
                    ("session_cancelled", "Séance annulée"),
                    ("payment_received", "Paiement reçu"),
                    ("invoice_ready", "Facture disponible"),
                    ("cert_expiry", "Alerte expiration certification"),
                    ("new_message", "Nouveau message"),
                    ("exercise_published", "Devoir publié"),
                    ("exercise_submitted", "Copie soumise"),
                    ("exercise_due_soon", "Devoir bientôt à rendre"),
                    ("exercise_overdue", "Devoir non rendu à échéance"),
                    ("correction_ready", "Correction disponible"),
                    ("recruitment", "Recrutement confirmé"),
                    ("stage_update", "Mise à jour stage"),
                    ("class_assignment", "Affectation à une matière"),
                    ("enrollment_update", "Mise à jour de scolarité"),
                    ("cert_level_changed", "Changement de niveau de certification"),
                    ("report_card_published", "Bulletin publié"),
                    ("timetable_reminder", "Rappel des cours du lendemain"),
                    ("revision_reminder", "Rappel de révision personnelle"),
                    ("holiday_declared", "Jour férié déclaré"),
                    ("new_cert_module", "Nouveau module de certification"),
                    ("followed_user_post", "Publication d'un profil suivi"),
                    ("engagement_tip", "Conseil de visibilité"),
                    ("system", "Système"),
                ],
                max_length=30,
            ),
        ),
    ]
