# Generated by Django 5.0.6 on 2026-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_remove_post_image_post_hashtags_follow_postimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=150, verbose_name="Titre"),
        ),
    ]
