# Generated by Django 5.0.6 on 2026-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="posts/videos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="video_duration_seconds",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
