# Generated by Django 5.0.6 on 2026-08-14 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0008_subject_coefficient'),
        ('users', '0007_companyprofile_brand_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('class_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rank', models.PositiveSmallIntegerField()),
                ('class_size', models.PositiveSmallIntegerField()),
                ('homeroom_comment', models.TextField(blank=True, verbose_name='Appréciation du professeur principal')),
                ('document', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='users.child')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('subject_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('coefficient', models.PositiveSmallIntegerField()),
                ('teacher_comment', models.CharField(blank=True, max_length=300)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_entries', to='grading.reportcard')),
            ],
            options={
                'verbose_name': 'Détail de matière du bulletin',
                'verbose_name_plural': 'Détails de matière du bulletin',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='Ex. 2025-2026', max_length=9, verbose_name='Année scolaire')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Numéro du trimestre')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nom (optionnel)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Trimestre en cours')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='users.directorprofile')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'ordering': ['-school_year', '-number'],
                'unique_together': {('establishment', 'school_year', 'number')},
            },
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='grading.term'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('eval_type', models.CharField(choices=[('homework', 'Devoir'), ('quiz', 'Interrogation'), ('exam', 'Composition')], default='homework', max_length=10)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='grading.term')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_excused', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.child')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grading.evaluation')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('evaluation', 'child')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('child', 'term')},
        ),
    ]
