# Generated by Django 5.0.6 on 2026-08-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        ('users', '0008_alter_child_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_establishment_name', models.CharField(blank=True, max_length=200)),
                ('declared_level', models.CharField(max_length=50, verbose_name='Niveau déclaré')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to='users.child')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='users.directorprofile')),
            ],
            options={
                'verbose_name': 'Demande de rattachement',
                'verbose_name_plural': 'Demandes de rattachement',
                'ordering': ['-created_at'],
            },
        ),
    ]
