# Generated by Django 5.0.6 on 2026-08-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_establishmentjoinrequest'),
        ('users', '0008_alter_child_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentjoinrequest',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='users.child'),
        ),
    ]
