# Generated by Django 5.0.6 on 2026-08-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_subject_coefficient"),
        ("grading", "0004_evaluation_max_score"),
        ("users", "0010_child_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectAppreciation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.CharField(blank=True, max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_appreciations",
                        to="users.child",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations",
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_appreciations",
                        to="grading.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appréciation de matière",
                "verbose_name_plural": "Appréciations de matière",
                "unique_together": {("subject", "child", "term")},
            },
        ),
    ]
