# Generated by Django 5.0.6 on 2026-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0005_subjectappreciation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="distinction",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("honor_roll", "Tableau d'honneur"),
                    ("honor_roll_encouragement", "Tableau d'honneur + Encouragements"),
                    ("honor_roll_congratulations", "Tableau d'honneur + Félicitations"),
                    ("refused", "Refusé(e)"),
                ],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="highest_average",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="Plus forte moyenne de la classe"
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="justified_absence_hours",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=5, verbose_name="Absences justifiées (heures)"
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="lowest_average",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="Plus faible moyenne de la classe"
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="sanction",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("work_warning", "Avertissement pour travail insuffisant"),
                    ("work_reprimand", "Blâme pour travail insuffisant"),
                    ("conduct_warning", "Avertissement pour mauvaise conduite"),
                    ("conduct_reprimand", "Blâme pour mauvaise conduite"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="unjustified_absence_hours",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=5, verbose_name="Absences non justifiées (heures)"
            ),
        ),
        migrations.AddField(
            model_name="subjectreportentry",
            name="category",
            field=models.CharField(
                choices=[("letters", "Lettres"), ("sciences", "Sciences"), ("other", "Autres")],
                default="other",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subjectreportentry",
            name="teacher_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Enseignant"),
        ),
    ]
