# Generated by Django 5.0.6 on 2026-08-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_timetableslot'),
        ('users', '0007_companyprofile_brand_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to='users.child')),
            ],
            options={
                'verbose_name': 'Objectif (bucket list)',
                'verbose_name_plural': 'Objectifs (bucket list)',
                'ordering': ['is_done', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Ce que je veux faire de ma vie')),
                ('related_subjects', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='life_goal', to='users.child')),
            ],
            options={
                'verbose_name': 'Objectif de vie',
                'verbose_name_plural': 'Objectifs de vie',
            },
        ),
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='users.child')),
            ],
            options={
                'verbose_name': 'Document personnel',
                'verbose_name_plural': 'Documents personnels',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to='users.child')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Note personnelle',
                'verbose_name_plural': 'Notes personnelles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
