# Generated by Django 5.0.6 on 2026-06-28 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Matiere",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=200)),
                ("adresse", models.TextField()),
                ("ville", models.CharField(max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("niveaux_enseignes", models.JSONField(default=list)),
                ("capacite_eleves", models.PositiveIntegerField(default=0)),
                ("docs_legaux", models.JSONField(default=list)),
                ("is_partenaire", models.BooleanField(default=False)),
                ("score_label", models.PositiveSmallIntegerField(default=0)),
                ("label_obtained_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "directeur",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "director"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etablissements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filieres",
                        to="admin_xporadia.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filière",
                "verbose_name_plural": "Filières",
                "ordering": ["etablissement", "code"],
                "unique_together": {("etablissement", "code")},
            },
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                ("niveau", models.CharField(max_length=20)),
                ("effectif", models.PositiveSmallIntegerField(default=0)),
                ("annee_scolaire", models.CharField(default="2024-2025", max_length=10)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="admin_xporadia.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["filiere", "niveau", "nom"],
                "unique_together": {("filiere", "nom", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'audit",
                "verbose_name_plural": "Logs d'audit",
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
                "indexes": [
                    models.Index(fields=["model_name", "object_id"], name="admin_xpora_model_n_a44f4f_idx"),
                    models.Index(fields=["user", "timestamp"], name="admin_xpora_user_id_245812_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClasseMatiere",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nb_heures_semaine", models.PositiveSmallIntegerField(default=2)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matieres",
                        to="admin_xporadia.classe",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"primary_role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_enseignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="admin_xporadia.matiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière de classe",
                "verbose_name_plural": "Matières de classes",
                "unique_together": {("classe", "matiere")},
            },
        ),
    ]
