# Generated by Django 5.0.6 on 2026-06-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutoringSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("child_name", models.CharField(max_length=100)),
                ("child_level", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                (
                    "mode",
                    models.CharField(
                        choices=[("home", "À domicile"), ("teacher", "Chez l'enseignant"), ("online", "En ligne")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("duration_min", models.PositiveSmallIntegerField(default=60)),
                ("address", models.TextField(blank=True)),
                ("note_for_teacher", models.TextField(blank=True, max_length=300)),
                ("gross_amount", models.PositiveIntegerField()),
                ("commission_rate", models.DecimalField(decimal_places=2, default=15, max_digits=4)),
                ("net_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("escrow_released", models.BooleanField(default=False)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("ongoing", "En cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                            ("disputed", "En litige"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_sessions_as_parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_sessions_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance de cours particulier",
                "verbose_name_plural": "Séances de cours particuliers",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TutoringReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_type", models.CharField(choices=[("parent", "Parent"), ("student", "Élève")], max_length=10)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True, max_length=150)),
                ("is_moderated", models.BooleanField(default=False)),
                ("teacher_reply", models.TextField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tutoring.tutoringsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis cours particulier",
                "verbose_name_plural": "Avis cours particuliers",
            },
        ),
        migrations.CreateModel(
            name="TutoringSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=50)),
                ("child_name", models.CharField(max_length=100)),
                ("monthly_rate", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_subscriptions_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement cours",
                "verbose_name_plural": "Abonnements cours",
            },
        ),
        migrations.AddIndex(
            model_name="tutoringsession",
            index=models.Index(fields=["teacher", "status"], name="tutoring_tu_teacher_925c07_idx"),
        ),
        migrations.AddIndex(
            model_name="tutoringsession",
            index=models.Index(fields=["parent", "status"], name="tutoring_tu_parent__cfbcc8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tutoringreview",
            unique_together={("session", "author")},
        ),
        migrations.AlterUniqueTogether(
            name="tutoringsubscription",
            unique_together={("parent", "teacher", "subject")},
        ),
    ]
