# Generated by Django 5.0.6 on 2026-06-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Élève"), ("parent", "Parent (lecture)")],
                        default="student",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Membre de classe",
            },
        ),
        migrations.CreateModel(
            name="VirtualClass",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("invite_code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_classes",
                        through="virtual_classes.ClassMember",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe virtuelle",
                "verbose_name_plural": "Classes virtuelles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField()),
                ("attachments", models.JSONField(default=list)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("published", "Publié"), ("closed", "Clôturé")],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "virtual_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="virtual_classes.virtualclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercice",
                "verbose_name_plural": "Exercices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("class", "Canal général"),
                            ("exercise", "Fil exercice"),
                            ("private", "Message privé"),
                        ],
                        default="class",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                ("attachments", models.JSONField(default=list)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_class_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discussion_messages",
                        to="virtual_classes.exercise",
                    ),
                ),
                (
                    "virtual_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="virtual_classes.virtualclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de classe",
                "verbose_name_plural": "Messages de classe",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="classmember",
            name="virtual_class",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="virtual_classes.virtualclass"),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("grade", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                (
                    "appreciation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Très bien"),
                            ("good", "Bien"),
                            ("to_review", "À revoir"),
                            ("fail", "Insuffisant"),
                        ],
                        max_length=15,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("annotations", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("submitted", "Soumis"), ("graded", "Corrigé")], default="submitted", max_length=15
                    ),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="virtual_classes.exercise",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soumission",
                "verbose_name_plural": "Soumissions",
                "ordering": ["submitted_at"],
                "unique_together": {("exercise", "student")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="classmember",
            unique_together={("virtual_class", "user")},
        ),
    ]
