# Generated by Django 5.0.6 on 2026-07-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject"),
        ("virtual_classes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualclass",
            name="members",
        ),
        migrations.RemoveField(
            model_name="classmessage",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="classmessage",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="classmessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="classmessage",
            name="virtual_class",
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="submission",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="student",
        ),
        migrations.AlterModelOptions(
            name="exercise",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cours / exercice",
                "verbose_name_plural": "Cours / exercices",
            },
        ),
        migrations.AlterModelOptions(
            name="virtualclass",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Espace numérique de matière",
                "verbose_name_plural": "Espaces numériques de matière",
            },
        ),
        migrations.RemoveField(
            model_name="virtualclass",
            name="invite_code",
        ),
        migrations.RemoveField(
            model_name="virtualclass",
            name="level",
        ),
        migrations.RemoveField(
            model_name="virtualclass",
            name="name",
        ),
        migrations.RemoveField(
            model_name="virtualclass",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="virtualclass",
            name="subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="virtual_class", to="academics.subject"
            ),
        ),
        migrations.DeleteModel(
            name="ClassMember",
        ),
        migrations.DeleteModel(
            name="ClassMessage",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
