# Generated by Django 5.0.6 on 2026-07-16 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_teachercomment"),
        ("virtual_classes", "0002_remove_virtualclass_members_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("submitted", "Soumis"), ("graded", "Corrigé")], default="submitted", max_length=15
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Note sur 20", max_digits=4, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="users.child"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="virtual_classes.exercise",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soumission",
                "verbose_name_plural": "Soumissions",
                "ordering": ["-submitted_at"],
                "unique_together": {("exercise", "child")},
            },
        ),
    ]
