# Generated by Django 5.0.6 on 2026-08-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_classes', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='due_soon_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='kind',
            field=models.CharField(choices=[('homework', 'Devoir'), ('exam', 'Examen')], default='homework', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
