# Generated by Django 5.0.6 on 2026-07-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_teacherinvitation"),
        ("users", "0005_teachercomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Inscrit"),
                            ("promoted", "Passé(e) en classe supérieure"),
                            ("repeating", "Redouble"),
                            ("withdrawn", "Parti(e) de l'établissement"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="users.child"
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academics.schoolclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-enrolled_at"],
                "unique_together": {("child", "school_class")},
            },
        ),
    ]
