# Generated by Django 5.0.6 on 2026-08-13 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetableslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='track_delegates',
            field=models.ManyToManyField(blank=True, related_name='delegated_departments', to=settings.AUTH_USER_MODEL, verbose_name='Enseignants autorisés à créer des filières ici'),
        ),
        migrations.AddField(
            model_name='track',
            name='class_delegates',
            field=models.ManyToManyField(blank=True, related_name='delegated_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Enseignants autorisés à créer des classes ici'),
        ),
    ]
