# Generated by Django 5.0.6 on 2026-08-13 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_department_track_delegates_track_class_delegates'),
        ('users', '0007_companyprofile_brand_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('timetable', 'Gestion des emplois du temps')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_delegations', to='users.directorprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_delegations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Délégation de tâche',
                'verbose_name_plural': 'Délégations de tâches',
                'unique_together': {('establishment', 'teacher', 'task')},
            },
        ),
    ]
