# Generated by Django 5.0.6 on 2026-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_taskdelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Coefficient'),
        ),
    ]
