# Generated by Django 5.0.6 on 2026-08-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_subject_coefficient"),
        ("grading", "0005_subjectappreciation"),
        ("users", "0010_child_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableslot",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_slots",
                to="grading.term",
                verbose_name="Trimestre (vide = toute l'année)",
            ),
        ),
        migrations.CreateModel(
            name="PersonalScheduleBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("title", models.CharField(max_length=200)),
                ("valid_from", models.DateField(verbose_name="Valide à partir du")),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au (vide = indéfini)"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_schedule_blocks",
                        to="users.child",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="academics.subject",
                        verbose_name="Matière (optionnel)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau personnel",
                "verbose_name_plural": "Créneaux personnels",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="PersonalBlockReminderLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="academics.personalscheduleblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de rappel de révision personnelle",
                "verbose_name_plural": "Journaux de rappel de révision personnelle",
                "unique_together": {("block", "date")},
            },
        ),
        migrations.CreateModel(
            name="PersonalScheduleException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("is_cancelled", models.BooleanField(default=False, verbose_name="Occurrence annulée")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="academics.personalscheduleblock",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exception de créneau personnel",
                "verbose_name_plural": "Exceptions de créneau personnel",
                "ordering": ["date"],
                "unique_together": {("block", "date")},
            },
        ),
        migrations.CreateModel(
            name="TimetableReminderLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="academics.schoolclass"
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de rappel d'emploi du temps",
                "verbose_name_plural": "Journaux de rappel d'emploi du temps",
                "unique_together": {("school_class", "date")},
            },
        ),
    ]
