# Generated by Django 5.0.6 on 2026-08-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_timetableslot_term_personalscheduleblock_and_more"),
        ("users", "0010_child_birth_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstablishmentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("report_card_distribution", "Remise de bulletins"),
                            ("meeting", "Réunion"),
                            ("holiday", "Jour férié"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("audience", models.JSONField(default=list, verbose_name="Public cible")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="users.directorprofile"
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="academics.schoolclass",
                        verbose_name="Classe concernée (vide = tout l'établissement)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement d'établissement",
                "verbose_name_plural": "Événements d'établissement",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
