# Generated by Django 5.0.6 on 2026-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_establishmentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_boarder",
            field=models.BooleanField(blank=True, null=True, verbose_name="Interne (régime)"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_ministry_assigned",
            field=models.BooleanField(default=True, verbose_name="Affecté(e) par le ministère"),
        ),
        migrations.AddField(
            model_name="subject",
            name="category",
            field=models.CharField(
                choices=[("letters", "Lettres"), ("sciences", "Sciences"), ("other", "Autres")],
                default="other",
                max_length=10,
                verbose_name="Groupe (bulletin)",
            ),
        ),
    ]
