# Generated by Django 5.0.6 on 2026-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_enrollment_is_boarder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdelegation",
            name="task",
            field=models.CharField(
                choices=[
                    ("timetable", "Gestion des emplois du temps"),
                    ("join_requests", "Gestion des demandes de rattachement"),
                ],
                max_length=20,
            ),
        ),
    ]
