# Generated by Django 5.0.6 on 2026-08-30 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_alter_taskdelegation_task"),
        ("users", "0012_directorprofile_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "taken_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions_taken",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.timetableslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appel",
                "verbose_name_plural": "Appels",
                "ordering": ["-date"],
                "unique_together": {("timetable_slot", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("absent", "Absent"), ("late", "En retard"), ("excused", "Absence justifiée")],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_exceptions",
                        to="users.child",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="academics.attendancesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exception d'appel",
                "verbose_name_plural": "Exceptions d'appel",
                "unique_together": {("session", "child")},
            },
        ),
    ]
