# Generated by Django 5.0.6 on 2026-08-30 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0013_attendancesession_attendanceexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishmentevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("report_card_distribution", "Remise de bulletins"),
                    ("meeting", "Réunion"),
                    ("holiday", "Jour férié"),
                    ("cancelled_class", "Cours annulé"),
                    ("other", "Autre"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TeacherAbsence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_absence",
                        to="academics.establishmentevent",
                    ),
                ),
                (
                    "timetable_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="academics.timetableslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence enseignant",
                "verbose_name_plural": "Absences enseignant",
                "unique_together": {("timetable_slot", "date")},
            },
        ),
    ]
