# Generated by Django 5.0.6 on 2026-07-05 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Téléphone")),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                (
                    "primary_role",
                    models.CharField(
                        choices=[
                            ("teacher", "Enseignant"),
                            ("director", "Directeur d'établissement"),
                            ("parent", "Parent d'élève"),
                            ("company", "Entreprise"),
                            ("trainer", "Formateur partenaire"),
                            ("admin", "Administrateur Xporadia"),
                        ],
                        max_length=20,
                        verbose_name="Rôle principal",
                    ),
                ),
                ("secondary_roles", models.JSONField(blank=True, default=list, verbose_name="Rôles secondaires")),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False, verbose_name="Compte vérifié")),
                (
                    "is_documents_validated",
                    models.BooleanField(default=False, verbose_name="Documents validés par Xporadia"),
                ),
                ("two_fa_enabled", models.BooleanField(default=False, verbose_name="2FA activée")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("school_name", models.CharField(max_length=255, verbose_name="Nom de l'école")),
                ("address", models.CharField(max_length=255, verbose_name="Adresse")),
                ("levels_taught", models.JSONField(blank=True, default=list, verbose_name="Niveaux enseignés")),
                (
                    "legal_documents",
                    models.FileField(blank=True, null=True, upload_to="school_docs/", verbose_name="Documents légaux"),
                ),
                ("student_count", models.PositiveIntegerField(blank=True, null=True, verbose_name="Effectif")),
                ("is_partner", models.BooleanField(default=False, verbose_name="École Partenaire Epsilon")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil directeur",
                "verbose_name_plural": "Profils directeurs",
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("account_verification", "Vérification de compte"),
                            ("password_reset", "Réinitialisation mot de passe"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code OTP",
                "verbose_name_plural": "Codes OTP",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="Localisation")),
                ("subscription_active", models.BooleanField(default=False, verbose_name="Abonnement actif")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil parent",
                "verbose_name_plural": "Profils parents",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("class_level", models.CharField(max_length=50, verbose_name="Classe")),
                ("target_subjects", models.JSONField(blank=True, default=list, verbose_name="Matières cibles")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="children", to="users.parentprofile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enfant",
                "verbose_name_plural": "Enfants",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subjects", models.JSONField(blank=True, default=list, verbose_name="Matières enseignées")),
                ("experience_years", models.PositiveSmallIntegerField(default=0, verbose_name="Années d'expérience")),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Tarif horaire (FCFA)"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="Localisation")),
                ("bio", models.TextField(blank=True, verbose_name="Bio professionnelle")),
                (
                    "identity_document",
                    models.FileField(
                        blank=True, null=True, upload_to="identity_docs/", verbose_name="Carte d'identité"
                    ),
                ),
                (
                    "available_for_tutoring",
                    models.BooleanField(default=False, verbose_name="Disponible cours particuliers"),
                ),
                (
                    "available_for_employment",
                    models.BooleanField(default=True, verbose_name="Disponible marché de l'emploi"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil enseignant",
                "verbose_name_plural": "Profils enseignants",
            },
        ),
        migrations.CreateModel(
            name="TeacherDiploma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Intitulé du diplôme")),
                ("file", models.FileField(upload_to="diplomas/", verbose_name="Fichier (PDF/image)")),
                ("obtained_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="diplomas", to="users.teacherprofile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Diplôme",
                "verbose_name_plural": "Diplômes",
            },
        ),
    ]
