# Generated by Django 5.0.6 on 2026-06-28 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Téléphone")),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                (
                    "primary_role",
                    models.CharField(
                        choices=[
                            ("teacher", "Enseignant"),
                            ("director", "Directeur d'établissement"),
                            ("parent", "Parent d'élève"),
                            ("company", "Entreprise"),
                            ("trainer", "Formateur partenaire"),
                            ("admin", "Administrateur Xporadia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("secondary_roles", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_documents_validated", models.BooleanField(default=False)),
                ("two_fa_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("school_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("student_count", models.PositiveIntegerField(default=0)),
                ("levels_taught", models.JSONField(default=list)),
                ("authorization_doc", models.FileField(blank=True, null=True, upload_to="school_docs/")),
                ("rccm_number", models.CharField(blank=True, max_length=100)),
                ("is_partner", models.BooleanField(default=False)),
                ("partner_score", models.PositiveSmallIntegerField(default=0)),
                ("subscription_active", models.BooleanField(default=False)),
                ("subscription_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil directeur",
                "verbose_name_plural": "Profils directeurs",
            },
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("subscription_active", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil parent",
                "verbose_name_plural": "Profils parents",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("school_level", models.CharField(max_length=50)),
                ("target_subjects", models.JSONField(default=list)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="children", to="users.parentprofile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enfant",
                "verbose_name_plural": "Enfants",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("subjects", models.JSONField(default=list)),
                ("levels", models.JSONField(default=list)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("diploma_files", models.JSONField(default=list)),
                ("available_for_job", models.BooleanField(default=True)),
                ("salary_expectation", models.PositiveIntegerField(blank=True, null=True)),
                ("available_for_tutoring", models.BooleanField(default=False)),
                ("hourly_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("tutoring_modes", models.JSONField(default=list)),
                ("radius_km", models.PositiveSmallIntegerField(default=5)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("avg_rating", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil enseignant",
                "verbose_name_plural": "Profils enseignants",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["primary_role"], name="users_user_primary_67ad29_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(fields=["available_for_job"], name="users_teach_availab_bf23a2_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(fields=["available_for_tutoring"], name="users_teach_availab_5f6518_idx"),
        ),
    ]
