# Generated by Django 5.0.6 on 2026-07-08 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255, verbose_name="Raison sociale")),
                ("sector", models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité")),
                ("address", models.CharField(max_length=255, verbose_name="Adresse")),
                (
                    "legal_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="company_docs/", verbose_name="Documents légaux"
                    ),
                ),
                ("is_partner", models.BooleanField(default=False, verbose_name="Entreprise partenaire premium")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil entreprise",
                "verbose_name_plural": "Profils entreprises",
            },
        ),
    ]
