# Generated by Django 5.0.6 on 2026-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_email",
            field=models.BooleanField(default=True, verbose_name="Notifications par email"),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_push",
            field=models.BooleanField(default=True, verbose_name="Notifications push"),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_sms",
            field=models.BooleanField(default=False, verbose_name="Notifications par SMS"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_visible",
            field=models.BooleanField(default=True, verbose_name="Profil public visible"),
        ),
    ]
