# Generated by Django 5.0.6 on 2026-07-14 13:02

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_deletion_requested_at_user_notify_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreRegistrationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(default=apps.users.models._generate_code, max_length=12, unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Session de formation (ex : Cocody, mars 2026)"
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preregistration_codes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preregistration_code_used",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de préinscription",
                "verbose_name_plural": "Codes de préinscription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="preregistration_code",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_profile",
                to="users.preregistrationcode",
            ),
        ),
    ]
