# Generated by Django 5.0.6 on 2026-07-14 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_preregistrationcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(max_length=1000, verbose_name="Commentaire")),
                ("is_anonymous", models.BooleanField(default=False, verbose_name="Publié anonymement")),
                ("is_hidden", models.BooleanField(default=False, verbose_name="Masqué par modération")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_teacher_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire sur profil enseignant",
                "verbose_name_plural": "Commentaires sur profils enseignants",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["teacher", "is_hidden"], name="users_teach_teacher_d70759_idx")],
            },
        ),
    ]
