# Generated by Django 5.0.6 on 2026-08-10 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teachercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte élève (une fois activé)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_role',
            field=models.CharField(choices=[('teacher', 'Enseignant'), ('director', "Directeur d'établissement"), ('parent', "Parent d'élève"), ('student', 'Élève'), ('company', 'Entreprise'), ('trainer', 'Formateur partenaire'), ('admin', 'Administrateur Xporadia')], max_length=20, verbose_name='Rôle principal'),
        ),
        migrations.CreateModel(
            name='StudentActivationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name="Email de l'élève")),
                ('token', models.CharField(editable=False, max_length=43, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_invites', to='users.child')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_student_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Invitation d'activation élève",
                'verbose_name_plural': "Invitations d'activation élève",
                'ordering': ['-created_at'],
            },
        ),
    ]
