# Generated by Django 5.0.6 on 2026-08-10 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_child_last_name_child_user_alter_user_primary_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='brand_primary_color',
            field=models.CharField(default='#0F172A', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur principale (hex)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='brand_secondary_color',
            field=models.CharField(default='#FB5406', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur invalide — format attendu : #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur secondaire (hex)'),
        ),
    ]
