# Generated by Django 5.0.6 on 2026-08-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_child_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='users.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='users.parentprofile')),
            ],
            options={
                'verbose_name': 'Demande de rattachement parent-enfant',
                'verbose_name_plural': 'Demandes de rattachement parent-enfant',
                'ordering': ['-created_at'],
            },
        ),
    ]
