# Generated by Django 5.0.6 on 2026-08-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_childclaimrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de naissance"),
        ),
    ]
