# Generated by Django 5.0.6 on 2026-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_child_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="birth_place",
            field=models.CharField(blank=True, max_length=100, verbose_name="Lieu de naissance"),
        ),
        migrations.AddField(
            model_name="child",
            name="matricule",
            field=models.CharField(blank=True, max_length=30, verbose_name="Matricule"),
        ),
        migrations.AddField(
            model_name="child",
            name="nationality",
            field=models.CharField(blank=True, default="Ivoirienne", max_length=50, verbose_name="Nationalité"),
        ),
        migrations.AddField(
            model_name="child",
            name="sex",
            field=models.CharField(
                blank=True, choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1, verbose_name="Sexe"
            ),
        ),
        migrations.AddField(
            model_name="directorprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email de contact de l'établissement"),
        ),
        migrations.AddField(
            model_name="directorprofile",
            name="establishment_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Code établissement"),
        ),
        migrations.AddField(
            model_name="directorprofile",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Établissement public"),
        ),
        migrations.AddField(
            model_name="directorprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Téléphone de l'établissement"),
        ),
    ]
