# Generated by Django 5.0.6 on 2026-08-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_child_birth_place_child_matricule_child_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorprofile",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="establishment_logos/", verbose_name="Logo de l'établissement"
            ),
        ),
    ]
