# Generated by Django 5.0.6 on 2026-09-06 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_directorprofile_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Nom du groupe")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founded_school_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe scolaire",
                "verbose_name_plural": "Groupes scolaires",
            },
        ),
        migrations.AddField(
            model_name="directorprofile",
            name="school_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="establishments",
                to="users.schoolgroup",
            ),
        ),
        migrations.CreateModel(
            name="SchoolGroupInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("accepted", "Acceptée"), ("rejected", "Rejetée")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="users.schoolgroup"
                    ),
                ),
                (
                    "invited_director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_group_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation de groupe scolaire",
                "verbose_name_plural": "Invitations de groupe scolaire",
                "ordering": ["-created_at"],
            },
        ),
    ]
