# Generated by Django 5.0.6 on 2026-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_schoolgroup_directorprofile_school_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_scope",
            field=models.CharField(
                choices=[
                    ("full", "Administrateur complet"),
                    ("moderation", "Modérateur (accréditations, bibliothèque, litiges)"),
                    ("accounts", "Gestionnaire de comptes"),
                    ("catalog", "Gestionnaire de contenu (formations, offres)"),
                ],
                default="full",
                max_length=20,
                verbose_name="Périmètre administrateur",
            ),
        ),
    ]
