# Generated by Django 5.0.6 on 2026-06-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("student_name", models.CharField(max_length=200)),
                ("student_level", models.CharField(max_length=50)),
                ("motivation", models.TextField(blank=True, max_length=600)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("accepted", "Acceptée"), ("rejected", "Refusée")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "director"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature stage",
                "verbose_name_plural": "Candidatures stage",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="InternshipConvention",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pdf_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Générée"),
                            ("sent", "Envoyée"),
                            ("signed_sch", "Signée école"),
                            ("signed_ent", "Signée entreprise"),
                            ("complete", "Complète"),
                        ],
                        default="generated",
                        max_length=15,
                    ),
                ),
                ("signed_by_school_at", models.DateTimeField(blank=True, null=True)),
                ("signed_by_company_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convention",
                        to="internships.internshipapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convention de stage",
                "verbose_name_plural": "Conventions de stage",
            },
        ),
        migrations.CreateModel(
            name="InternshipOffer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=100)),
                ("missions", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("3e", "3ème"),
                            ("2nde", "Seconde"),
                            ("1ere", "Première"),
                            ("terminale", "Terminale"),
                        ],
                        max_length=15,
                    ),
                ),
                ("duration_weeks", models.PositiveSmallIntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("places", models.PositiveSmallIntegerField(default=1)),
                ("city", models.CharField(max_length=100)),
                ("skills_wanted", models.JSONField(default=list)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "company"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre de stage",
                "verbose_name_plural": "Offres de stage",
                "ordering": ["-is_premium", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="internships.internshipoffer",
            ),
        ),
        migrations.CreateModel(
            name="InternshipEvaluation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "evaluator_type",
                    models.CharField(
                        choices=[("company", "Entreprise → Stagiaire"), ("student", "Stagiaire → Entreprise")],
                        max_length=10,
                    ),
                ),
                ("punctuality", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("initiative", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("integration", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("skills", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("global_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, max_length=500)),
                ("attestation_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="internships.internshipconvention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation stage",
                "verbose_name_plural": "Évaluations stage",
                "unique_together": {("convention", "evaluator_type")},
            },
        ),
        migrations.CreateModel(
            name="InternshipJournal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("content", models.TextField()),
                ("photos", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="internships.internshipconvention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de stage",
                "verbose_name_plural": "Journaux de stage",
                "ordering": ["date"],
                "unique_together": {("convention", "date")},
            },
        ),
    ]
