# Generated by Django 5.0.6 on 2026-08-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipconvention',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
        migrations.AddField(
            model_name='internshipconvention',
            name='position_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intitulé du poste'),
        ),
    ]
