# Generated by Django 5.0.6 on 2026-08-15 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internshipconvention_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmosphere', models.PositiveSmallIntegerField(help_text='Ambiance, accueil (1-5)')),
                ('mentorship', models.PositiveSmallIntegerField(help_text="Qualité de l'encadrement (1-5)")),
                ('role_accuracy', models.PositiveSmallIntegerField(help_text='Conformité au poste annoncé (1-5)')),
                ('learning_value', models.PositiveSmallIntegerField(help_text='Apport pédagogique (1-5)')),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_review', to='internships.internshipconvention')),
            ],
            options={
                'verbose_name': 'Avis entreprise',
                'verbose_name_plural': 'Avis entreprise',
            },
        ),
    ]
