# Generated by Django 5.0.6 on 2026-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0003_companyreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipoffer",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="internship_offers/"),
        ),
    ]
