# Generated by Django 5.0.6 on 2026-08-17 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0004_internshipoffer_cover_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipOfferSchoolLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Envoyée à l'établissement"), ("published", "Publiée par l'établissement")],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_links",
                        to="internships.internshipoffer",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "director"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship_offer_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diffusion offre → établissement",
                "verbose_name_plural": "Diffusions offre → établissement",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="internshipofferschoollink",
            constraint=models.UniqueConstraint(fields=("offer", "school"), name="unique_offer_school_link"),
        ),
    ]
