# Generated by Django 5.0.6 on 2026-06-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pedagogy", "Pédagogie générale"),
                            ("didactics", "Didactique disciplinaire"),
                            ("management", "Gestion de classe"),
                            ("ethics", "Éthique professionnelle"),
                            ("leadership", "Leadership pédagogique"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("objectives", models.JSONField(default=list)),
                ("prerequisites", models.TextField(blank=True)),
                ("duration_hours", models.PositiveSmallIntegerField(default=8)),
                ("price", models.PositiveIntegerField(help_text="FCFA")),
                (
                    "target_level",
                    models.CharField(
                        choices=[("bronze", "Bronze"), ("silver", "Argent"), ("gold", "Or")],
                        default="bronze",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module de formation",
                "verbose_name_plural": "Modules de formation",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="SessionEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("paid", "Payé"), ("refunded", "Remboursé")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attendance_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Inscription session",
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=300)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity", models.PositiveSmallIntegerField(default=30)),
                ("enrolled_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifiée"),
                            ("ongoing", "En cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_sessions",
                        through="certification.SessionEnrollment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="certification.trainingmodule",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "trainer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de formation",
                "verbose_name_plural": "Sessions de formation",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="sessionenrollment",
            name="session",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="certification.trainingsession"),
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_retake", models.BooleanField(default=False)),
                ("answers", models.JSONField(default=dict)),
                ("score_auto", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("score_manual", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("score_attendance", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("score_total", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("trainer_feedback", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En cours"),
                            ("submitted", "Soumis"),
                            ("graded", "Noté"),
                            ("passed", "Réussi"),
                            ("failed", "Échoué"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to="certification.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative d'examen",
                "verbose_name_plural": "Tentatives d'examen",
                "ordering": ["-started_at"],
                "unique_together": {("teacher", "session", "is_retake")},
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "question_type",
                    models.CharField(
                        choices=[("mcq", "QCM"), ("open", "Question ouverte"), ("tf", "Vrai/Faux")], max_length=5
                    ),
                ),
                ("text", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(blank=True, max_length=500)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Facile"), ("medium", "Moyen"), ("hard", "Difficile")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("points", models.PositiveSmallIntegerField(default=1)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="certification.trainingmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question d'examen",
                "verbose_name_plural": "Questions d'examen",
                "indexes": [models.Index(fields=["module", "difficulty"], name="certificati_module__6bb4e2_idx")],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "level",
                    models.CharField(
                        choices=[("bronze", "Bronze"), ("silver", "Argent"), ("gold", "Or")], max_length=10
                    ),
                ),
                ("score_total", models.DecimalField(decimal_places=2, max_digits=5)),
                ("qr_code", models.CharField(max_length=100, unique=True)),
                ("pdf_url", models.URLField(blank=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateField()),
                ("is_valid", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certification",
                        to="certification.examattempt",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to="certification.trainingmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(fields=["qr_code"], name="certificati_qr_code_a04d53_idx"),
                    models.Index(fields=["teacher", "is_valid"], name="certificati_teacher_dae799_idx"),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="sessionenrollment",
            unique_together={("session", "teacher")},
        ),
    ]
