# Generated by Django 5.0.6 on 2026-07-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attempts",
                to="certification.trainingmodule",
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attempts",
                to="certification.trainingsession",
            ),
        ),
    ]
