# Generated by Django 5.0.6 on 2026-07-16 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0002_alter_examattempt_unique_together_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionenrollment",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_enrollment",
                to="payments.payment",
            ),
        ),
    ]
