# Generated by Django 5.0.6 on 2026-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_sessionenrollment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='points_awarded',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='points',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
