# Generated by Django 5.0.6 on 2026-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_certification_points_awarded_trainingmodule_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
