# Generated by Django 5.0.6 on 2026-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0005_certification_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodule",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="certification_modules/"),
        ),
    ]
