# Generated by Django 5.0.6 on 2026-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0006_trainingmodule_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="level",
            field=models.CharField(
                choices=[
                    ("zero", "Zéro"),
                    ("bronze", "Bronze"),
                    ("silver", "Argent"),
                    ("gold", "Or"),
                    ("platinum", "Platine"),
                    ("diamond", "Diamant"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="target_level",
            field=models.CharField(
                choices=[
                    ("zero", "Zéro"),
                    ("bronze", "Bronze"),
                    ("silver", "Argent"),
                    ("gold", "Or"),
                    ("platinum", "Platine"),
                    ("diamond", "Diamant"),
                ],
                default="bronze",
                max_length=10,
            ),
        ),
    ]
