# Generated by Django 5.0.6 on 2026-06-28 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=50)),
                ("levels", models.JSONField(default=list)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("cdi", "CDI"), ("cdd", "CDD"), ("vacation", "Vacation"), ("interim", "Intérim")],
                        max_length=15,
                    ),
                ),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cert_level_required",
                    models.CharField(
                        choices=[("bronze", "Bronze"), ("silver", "Argent"), ("gold", "Or")],
                        default="bronze",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending", "En attente de modération"),
                            ("active", "Active"),
                            ("closed", "Clôturée"),
                            ("expired", "Expirée"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "director"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre d'emploi",
                "verbose_name_plural": "Offres d'emploi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cover_letter", models.TextField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("viewed", "Vue"),
                            ("interview", "Entretien"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                            ("withdrawn", "Retirée"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="employment.joblisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("salary_agreed", models.PositiveIntegerField()),
                ("commission_rate", models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ("commission_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payée"),
                            ("failed", "Échouée"),
                            ("waived", "Dispensée"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attestation_url", models.URLField(blank=True)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employment.jobapplication",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "director"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments_as_school",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recrutement",
                "verbose_name_plural": "Recrutements",
                "ordering": ["-confirmed_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployerReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("atmosphere", models.PositiveSmallIntegerField()),
                ("contract_respect", models.PositiveSmallIntegerField()),
                ("working_conditions", models.PositiveSmallIntegerField()),
                ("payment_timeliness", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True, max_length=500)),
                ("is_moderated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recruitment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_review",
                        to="employment.recruitment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis employeur",
                "verbose_name_plural": "Avis employeurs",
            },
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["status"], name="employment__status_a3f129_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["subject", "city"], name="employment__subject_e2a6a9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("teacher", "listing")},
        ),
    ]
