# Generated by Django 5.0.6 on 2026-07-14 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="targeted_teachers",
            field=models.ManyToManyField(
                blank=True, related_name="targeted_job_listings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="levels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="status",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("active", "Active"), ("closed", "Clôturée"), ("expired", "Expirée")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="JobSeekingRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subjects", models.JSONField(blank=True, default=list)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"primary_role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_seeking_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'emploi",
                "verbose_name_plural": "Demandes d'emploi",
                "ordering": ["-created_at"],
            },
        ),
    ]
