# Generated by Django 5.0.6 on 2026-08-11 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_joblisting_targeted_teachers_alter_joblisting_levels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='contract_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('vacation', 'Vacation'), ('interim', 'Intérim')], default='cdi', max_length=10),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='hourly_rate_billed',
            field=models.PositiveIntegerField(blank=True, help_text="FCFA/heure facturés à l'établissement", null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='hourly_rate_teacher',
            field=models.PositiveIntegerField(blank=True, help_text="FCFA/heure versés à l'enseignant", null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='salary_agreed',
            field=models.PositiveIntegerField(blank=True, help_text='Salaire mensuel — uniquement pertinent pour un CDI', null=True),
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hourly_rate_teacher', models.PositiveIntegerField()),
                ('hourly_rate_billed', models.PositiveIntegerField()),
                ('gross_amount', models.PositiveIntegerField(help_text="Montant versé à l'enseignant (FCFA)")),
                ('billed_amount', models.PositiveIntegerField(help_text="Montant facturé à l'établissement (FCFA)")),
                ('xporadia_margin', models.PositiveIntegerField(help_text='billed_amount - gross_amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='employment.recruitment')),
            ],
            options={
                'verbose_name': 'Ligne de paie',
                'verbose_name_plural': 'Lignes de paie',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('recruitment', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='employment.payrollentry')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction du portefeuille',
                'verbose_name_plural': 'Transactions du portefeuille',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkedHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('payroll_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worked_hours', to='employment.payrollentry')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_hours', to='employment.recruitment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heures travaillées',
                'verbose_name_plural': 'Heures travaillées',
                'ordering': ['-date'],
                'unique_together': {('recruitment', 'date')},
            },
        ),
    ]
