# Generated by Django 5.0.6 on 2026-08-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_recruitment_contract_type_and_more'),
        ('payments', '0002_payment_card_holder_name_payment_card_last4_and_more'),
        ('users', '0009_childclaimrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('total_amount', models.PositiveIntegerField(help_text='Somme des PayrollEntry.billed_amount du mois (FCFA)')),
                ('status', models.CharField(choices=[('unpaid', 'Non payée'), ('paid', 'Payée')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.directorprofile')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_invoice', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Facture établissement',
                'verbose_name_plural': 'Factures établissement',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('establishment', 'period_year', 'period_month')},
            },
        ),
    ]
