# Generated by Django 5.0.6 on 2026-08-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employment", "0004_establishmentinvoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="cert_level_required",
            field=models.CharField(
                choices=[
                    ("zero", "Zéro"),
                    ("bronze", "Bronze"),
                    ("silver", "Argent"),
                    ("gold", "Or"),
                    ("platinum", "Platine"),
                    ("diamond", "Diamant"),
                ],
                default="bronze",
                max_length=10,
            ),
        ),
    ]
