# Generated by Django 5.0.6 on 2026-09-06 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0015_attendancesession_created_by"),
        ("users", "0013_schoolgroup_directorprofile_school_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplinaryIncident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurred_on", models.DateField()),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("minor", "Mineur"), ("moderate", "Modéré"), ("serious", "Grave")], max_length=10
                    ),
                ),
                (
                    "sanction",
                    models.CharField(
                        choices=[
                            ("none", "Aucune"),
                            ("warning", "Avertissement"),
                            ("reprimand", "Blâme"),
                            ("detention", "Retenue"),
                            ("suspension", "Exclusion temporaire"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("parent_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_incidents",
                        to="users.child",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_incidents",
                        to="users.directorprofile",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_incidents",
                        to="academics.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at"],
            },
        ),
    ]
